### ISSUE TITLE
Further speed improvements

### ISSUE THREAD

**Issue by llrs** [termehs/multigraphr#5]
I saw a post in Mastodon about [improving the efficiency of the package](https://fosstodon.org/@schochastics/111969099166286631). If it is something that matters it can be improved further.

For symmetric matrices you can change this:

```r
for (i in 1:n) {
	for (j in 1:n) {
		if (i != j ) {
			mat[i,j] <- calc
		}
...

```

By this:

```r
for (i in 1:n) {
	for (j in seq_len(i)) {
		if (i != j ) {
			mat[i,j] <- calc
			mat[j, i] <- mat[i, j]
		}
...
```

This should speed the time spent on these matrices and reduce the time to half of it.

I think this is applicable to at least 9 occasions, so it might make the model `iea_model` at least 3 times faster and `get_edge_assignment_probs` twice faster. 
I could create a PR if you wish (but I don't have time to do it right now)

**Comment by termehs** [comment]
Many thanks for suggesting this :) Happy to accept a PR whenever you get the chance so no rush
